### ISSUE TITLE
Strange....

### ISSUE THREAD

**Issue by MSF-Jarvis** [DsLNeXuS/Rashr#14]
When I try to flash any recovery or kernel/boot image on HTC Explorer A310e Rashr throws an error, something like "error executing /data/data/de.mkrtchyan.recoverytools**%^#$%&&**". But when i create a copy of the image at "/data/data/de.mkrtchyan.recoverytools/files" and then navigate to the original copy i.e. the one on the sdcard and then flash it it flashes perfectly. What's Happening ??

**Comment by DsLNeXuS** [comment]
Hello,
thanks for your report.
Because of Android restrictions on some systems is the busybox binary not able to open or use files from sdcard (or internal memory) so Rashr creates a copy of the Image into the app data directory. Could you report it me over Rashr as an email? Please comment it and don't forget to add the logs

Aschot Mkrtchyan

**Comment by MSF-Jarvis** [comment]
I'll do it soon. Thanks for replying

**Comment by MSF-Jarvis** [comment]
I've sent it through and also attached the entire log along with whatever Rashr automatically adds.
