### ISSUE TITLE
Device Detection Issues and Fake Flashing

### ISSUE THREAD

**Issue by MSF-Jarvis** [DsLNeXuS/Rashr#15]
I tried out Rashr on a Samsung Galaxy Tab 2 P3100 but it gets detected as a P3110. Also when I flashed a recovery from storage, It shows success but I reboot to see the ugly android system recovery again.(Maybe it's a problem with all Samsungs or with older ones, I don't exactly know....)

**Comment by msfjarvis** [comment]
I sent the logs using Rashr's inbuilt tool.

**Comment by jedie** [comment]
I have the galaxy tab p5110 and also get downloads for 3110, too.

**Comment by MSF-Jarvis** [comment]
I think that's some problem with Samsung devices. Maybe the generic device detection algorithm used by Rashr doesn't work that good with older kind of Galaxy devices.

**Comment by DsLNeXuS** [comment]
Yes... on some Samsung devices flashing over DD isn't working. The problem is if you execute the DD command everything seems to be ok.
@jedie send me a report and send me your email adress over XDA or PN. I get too many emails ~ 200/Day
I'm sorry but I can't respond or react directly I'm realy busy at the moment
